### ISSUE TITLE
Syntax Errors...!!!

### ISSUE THREAD

**Issue by IOSDevelopereHere** [MercuryProtocol/web3.swift#4]
I have successfully installed web3 using cocoapods and it has installed.when i build the project its giving alot of errors in CryptoSwift.
Need Help...
![screen shot 2018-04-11 at 4 20 32 pm](https://user-images.githubusercontent.com/37739290/38613754-55018e86-3da4-11e8-8425-6ea4ff623a8b.png)

**Comment by ougyosen** [comment]
I got the same issue and found that my swift version is 4.0.
The newest version of CryptoSwift is 0.9 that support swift 4.1.
Than I add below to my podfile, it works.
  pod 'CryptoSwift', '0.8.3'

**Comment by IOSDevelopereHere** [comment]
I have Updated Xcode and resolved the issue...
